export const ADD_NEW_DEVICE = 'ADD_NEW_DEVICE';
export const UPDATE_DEVICE = 'UPDATE_DEVICE';
export const SET_DEVICES = 'SET_DEVICES';
export const DELETE_DEVICE = 'DELETE_DEVICE';
export const SET_DETECTED_DEVICES = 'SET_DETECTED_DEVICES';
export const SET_DEVICE_LOGS = 'SET_DEVICE_LOGS';
